### ISSUE TITLE
Deleting a workflow in cy graph (right click) deletes the complete WF

### ISSUE THREAD

**Issue by kantale** [kantale/OpenBioC#119]
Reproduce:
https://www.openbio.eu/platform/w/hapmap3_pca/2
Fork
Right click in pca_plink_and_plot/1 (workflow node)
Select Delete

The complete WF is gone!

**Comment by giatrakister** [comment]
when an element (i.e. tool1) belongs to more than one wf (i.e. WF1 and WF2), when one of the two wfs is deleted then tool1 is deleted too which is not correct.
Possible fix, on delete function, check belong_to field while delteing successors of a node.
(should we keep somehow all the parents of a node???)

**Comment by kantale** [comment]
How to reproduce:
Create:
* Workflow: name:WF1, input: inp_wf1, step: step_wf1 connect with: inp_wf1
* Workflow: name:WF2, input: inp_wf2, DND: WF1, step: step_wf2 connect with: inp_wf1, inp_wf2
* Fork WF2
* Load WF2/2. Right click and delete WF1. 

**Step: step_wf2 gets deleted!**

**Comment by kantale** [comment]
To resolve this issue we need to re-design the complete "delete a node" feature. The new specs are:

* When deleting a step:
   * Check if this step is called by another step or calls another step. If yes throw an error message.
   * Check if this step sets an output or reads an input. If yes throw an error.
   * If both conditions are ok, Delete the step
* When deleting an input/output
   * Check if this input is read by a step or this output is set by a step. If yes throw an error message. 
   * If no, delete this node. Make sure that the inputs/outputs of the node are updated in the WF UI.
* When deleting a tool:
   * Check if this tool is used by any step. If yes throw an error
   * Check if this tool is a dependency to another tool that is used by any step. If yes throw an error.
   * If both conditions are ok, delete this tool
* When deleting a Workflow.
   * Check if this is the root WF. If yes, throw an error message and do not delete the WF.
   * Make a list of all predecessor WFs of this WF (called them "pred_WFs").
   * Traverse all successor nodes of this WF. For each node:
      * If this is a step node. Check that it is not called or calls another step that belongs to pred_WFs. If yes throw an error message and don't delete the WF.
      * If this is an input/output node. Check if that is not set or read from another step that belongs to pred_WFs. If yes throw an error message and don't delete the WF.
      * If this is a tool node:
         * Check if this tool is used by any step that belongs in pred_WFs. If yes throw an error and do not delete this WF.
         * Check is this tool is a dependency to another tool that is called by a step that belongs in pred_WFs. If yes throw an error and do not delete this WF
   * If all these conditions are False for every successor node, then traverse again the successor nodes of this WF and delete every node. Then, delete this WF node.
