### ISSUE TITLE
step is lost while being edit in workflow fork action

### ISSUE THREAD

**Issue by giatrakister** [kantale/OpenBioC#121]
When a workflow is forked , steps can be edited. If a step is the main one, and user updates it;s script, whne saving an error message appears "there is already a main step for this workflow". If after that the workflow is saved that steps is no longer in place.

**Comment by kantale** [comment]
confirmed

**Comment by kantale** [comment]
A solution is to make ```node.data.main=false;``` for all steps that are DnDed from other WFs. 
A side-effect is that we would not be able to locate the main steps of non-root WFs. 

A solution to this is to visually distinguish the main steps of the root WF, with the main steps of non-root WFs.
A possible schema is:
* main step of a root WF: RED BORDER
* main step of a non-root WF: BLACK BORDER

**Comment by kantale** [comment]
The "If after that the workflow is saved that steps is no longer in place." is a separate bug..

How to reproduce: 
* Create a WF with a step that is NOT main
* Add a step thay is main
* Click the "non-main" step
* Click the main check box
* Click update

The node is deleted
